a=int(input("So tien ban dau: "))
b=int(input("So thang gui: "))
c=float(input("Lai suat/ thang: "))
m=a*(1+b*c)
print("Voi so tien ban dau "+ str(a)+", sau "+str(b)+" thang gui, lai suat "+str(c)+"/thang")
print("Thi so tien nhan duoc cuoi ky la: ",m)